spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
          jwt-set-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/certs


